### ISSUE TITLE
POST body is split on new lines, only last line is evaluated

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/pman#143]
Working example, because `pfurl` (mostly) minifies the input

```bash
pfurl --verb POST --raw --http localhost:5040/api/v1/cmd --jsonwrapper 'payload' --msg \
'{  "action": "run",
    "meta":  {
        "cmd":      "ls /share",
        "auid":     "rudolphpienaar",
        "jid":      "a-job-id-2",
        "threaded": true,
        "container":   {
                "target": {
                    "image":        "fnndsc/pl-simpledsapp"
                },
                "manager": {
                    "image":        "fnndsc/swarm",
                    "app":          "swarm.py",
                    "env":  {
                        "shareDir":     "/hostFS/storeBase",
                        "serviceType":  "docker",
                        "serviceName":  "testService"
                    }
                }
        }
    }
}'
```

Supposed to be an equivalent call using `curl` but does not work:

```bash
curl http://localhost:8012/api/v1/cmd --data \
    '{ "payload": {  "action": "run",
        "meta":  {
            "cmd":      "ls /share",
            "auid":     "rudolphpienaar",
            "jid":      "a-job-id-2",
            "threaded": true,
            "container":   {
                    "target": {
                        "image":        "fnndsc/pl-simpledsapp"
                    },
                    "manager": {
                        "image":        "fnndsc/swarm",
                        "app":          "swarm.py",
                        "env":  {
                            "shareDir":     "/hostFS/storeBase",
                            "serviceType":  "docker",
                            "serviceName":  "testService"
                        }
                    }
            }
        }
    }}'
```

Logs

```
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | Listener ID - 10: process() - handling request
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | 
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ***********************************************
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ***********************************************
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | 2021-02-06 19:20:02.125230 incoming data stream
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ***********************************************
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | len = 1020
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ***********************************************
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | POST /api/v1/cmd HTTP/1.1
Host: localhost:5010
User-Agent: curl/7.75.0
Accept: */*
Content-Length: 861
Content-Type: application/x-www-form-urlencoded

{ "payload": {  "action": "run",
            "meta":  {
                "cmd":      "ls /share",
                "auid":     "rudolphpienaar",
                "jid":      "a-job-id-2",
                "threaded": true,
                "container":   {
                        "target": {
                            "image":        "fnndsc/pl-simpledsapp"
                        },
                        "manager": {
                            "image":        "fnndsc/swarm",
                            "app":          "swarm.py",
                            "env":  {
                                "shareDir":     "/hostFS/storeBase",
                                "serviceType":  "docker",
                                "serviceName":  "testService"
                            }
                        }
                }
            }
        }}

2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ***********************************************
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | Request = ...
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | ['POST /api/v1/cmd HTTP/1.1\r', 'Host: localhost:5010\r', 'User-Agent: curl/7.75.0\r', 'Accept: */*\r', 'Content-Length: 861\r', 'Content-Type: application/x-www-form-urlencoded\r', '\r', '{ "payload": {  "action": "run",', '            "meta":  {', '                "cmd":      "ls /share",', '                "auid":     "rudolphpienaar",', '                "jid":      "a-job-id-2",', '                "threaded": true,', '                "container":   {', '                        "target": {', '                            "image":        "fnndsc/pl-simpledsapp"', '                        },', '                        "manager": {', '                            "image":        "fnndsc/swarm",', '                            "app":          "swarm.py",', '                            "env":  {', '                                "shareDir":     "/hostFS/storeBase",', '                                "serviceType":  "docker",', '                                "serviceName":  "testService"', '                            }', '                        }', '                }', '            }', '        }}']
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | Using token authentication: False
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | Request authorized
2021-02-06 19:20:02  |    cbf53302ee63 |                    pman.py:Listener.process() | json_payload = '        }}'
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/pman/pman.py", line 671, in run
    resultFromProcessing    = self.process(request)
  File "/usr/local/lib/python3.8/dist-packages/pman/pman.py", line 2191, in process
    d_payload           = json.loads(json_payload)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 9 (char 8)
```

Working `curl` example

```bash
curl http://localhost:5010/api/v1/cmd --data '{"payload": {"action": "run", "meta": {"cmd": "ls/share", "auid": "rudolphpienaar", "jid": "not-a-uuid-2", "threaded": true, "container": {"target": {"image": "fnndsc/pl-simpledsapp"}, "manager": {"image": "fnndsc/swarm", "app": "swarm.py", "env": {"shareDir": "/wow/hostFS/a_folder", "serviceType": "docker", "serviceName": "testService"}}}}}}'
```

**Comment by jennydaman** [comment]
Probably fixed by 18f79200d549c00461187addf4f80dd9740b0a6b
